### ISSUE TITLE
Calling translate multiple times result in multiple "translate" in DOM

### ISSUE THREAD

**Issue by ghn** [trinary/d3-transform#10]
Hi,
plugin works fine except when calling

.attr("transform", translate)
.attr("transform", translate)
.attr("transform", translate)

==> we've got 3 "translate" in the same "transform" attribute.

**Comment by seliopou** [comment]
Hey there. Thanks for the filing the issue, but I couldn't reproduce with the information given. Can you provide a complete, runnable, example that exercises the bug?

**Comment by ghn** [comment]
oops, in fact the problem came from my own code. Sorry :)
