### ISSUE TITLE
Not available in bower?

### ISSUE THREAD

**Issue by cnjsstong2** [trinary/d3-transform#12]
Hi trinary, did you pull it back from bower? Couldn't find it on http://bower.io/search/?q=d3-transform .

**Comment by trinary** [comment]
Weird. Just tried to re-register/update it and it's telling me it is a duplicate and I can't push. Thanks for the heads up, I'll see what bower thinks is going on with this.

**Comment by trinary** [comment]
Ah. Hey @mbostock, there's a bower entry under d3/d3-transform for your fork of this that (I think) is private. What's the best way to handle distribution for this sort of thing?

**Comment by mbostock** [comment]
Hrm. I don’t think I registered anything for d3-transform. Am I doing this wrong? (I don’t use bower.)

```
$ bower unregister d3-transform
? You are about to remove component "d3-transform" from the bower registry (https://bower.herokuapp.com). It is generally considered bad behavior to remove versions of a library that others are depending on. Are you really sure? YesN) y
bower unregister    d3-transform
bower EFORBIDDEN    Must be a collaborator on GitHub.com repository
```

**Comment by trinary** [comment]
Yep, it's pointing into the d3 project, no fork there anymore. Not sure how it got created, I'll see if a bower support-type person can help fix it.
```
$ bower info d3-transform
bower not-cached    git://github.com/d3/d3-transform.git#*
bower resolve       git://github.com/d3/d3-transform.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/d3/d3-transform.git", exit code of #128

Additional error details:
fatal: remote error:
  Repository not found.
```

**Comment by mbostock** [comment]
I can create a temporary repo, unregister, and then delete.

**Comment by mbostock** [comment]
Okay, it worked.

**Comment by trinary** [comment]
Excellent, thank you!

**Comment by trinary** [comment]
Published a new bower component from my repo.

**Comment by cnjsstong2** [comment]
Great! Thank you.
