### ISSUE TITLE
url for this

### ISSUE THREAD

**Issue by altsheets** [trinary/d3-transform#13]
Would be nice if this got a URL comparable to
    https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js

There there's no need for me to copy the script to local.

I also tried to directly include
    https://raw.githubusercontent.com/trinary/d3-transform/master/src/d3-transform.js

but that results in

    Refused to execute script from 
    'https://raw.githubusercontent.com/trinary/d3-transform/master/src/d3-transform.js' 
    because its MIME type ('text/plain') is not executable, 
    and strict MIME type checking is enabled.

Thanks! 

For me, d3-transform [is very useful](https://github.com/altsheets/d3-animatelogo)!

**Comment by trinary** [comment]
Yup, Github intentionally sets the type of its response headers for raw.githubusercontent.com to discourage people from hotlinking. I'll see about a CDN host, is cdnjs still the standard?

**Comment by altsheets** [comment]
> I'll see about a host,
Nice, thanks a lot.

> is cdnjs still the standard?
no idea, these are my first days with D3 ... :-) amazing ...

**Comment by timelyportfolio** [comment]
As a quick and easy first step, you could try [RawGit](https://rawgit.com)  which yields the links

*  `dev/testing` https://rawgit.com/trinary/d3-transform/master/src/d3-transform.js
*  `url in production` https://cdn.rawgit.com/trinary/d3-transform/master/src/d3-transform.js

Also, you could easily do a `gh-pages` branch (see [creating gh-pages](https://help.github.com/articles/creating-project-pages-manually/)) with the file.  If you can start a blank gh-pages branch as in the link, I'll be happy to submit pull with the .js and your example that will then be available at http://trinary.github.io/d3-transform.

**Comment by altsheets** [comment]
Superb. Already included that into my project:  
* https://github.com/altsheets/d3-animatelogo/blob/master/animatelogo.html#L24-L27
* so I could [delete all d3-transform files](https://github.com/altsheets/d3-animatelogo/commit/352c4c03b89fe161e12a8a1667f4eb34a08e6791#diff-1) from my repo

Solved. At least short term ("[The catch: this is a free service, so there are no uptime or support guarantees.](https://rawgit.com/)" )

Thanks a lot for your help. How do you like my funny [d3-transform-animation](http://altsheets.ddns.net/d3/animatelogo/) ? :-)

**Comment by trinary** [comment]
Huge delay on this, but I've submitted https://github.com/cdnjs/cdnjs/issues/5836 for CDNJS inclusion.

**Comment by trinary** [comment]
At long last, we're up on cdnjs :) https://cdnjs.cloudflare.com/ajax/libs/d3-transform/1.0.4/d3-transform.min.js

**Comment by altsheets** [comment]
thx!
