### ISSUE TITLE
Append one transform chain to another (concat chains)

### ISSUE THREAD

**Issue by sompylasar** [trinary/d3-transform#14]
If you have two existing transform objects, it would be great if you could append one to another after constructing. This is required for better transform reuse.

Example (zoom with a center point):
```javascript
import d3Transform from 'd3-transform';

const zoomTransform = d3Transform().scale(1.5);

// The 'x' and 'y' are calculated from the bounding box.
const originForwardTransform= d3Transform().translate([ x, y ]);
const originBackwardTransform= d3Transform().translate([ -x, -y ]);

// Notice the order.
const zoomCenteredTransform = d3Transform()
  .concat(originForwardTransform)
  .concat(zoomTransform)
  .concat(originBackwardTransform);
```

**Comment by seliopou** [comment]
Should be easy to implement. `seq` may be a better name than `concat`, as it connotes more of an operation on actions rather than slapping together data.
