### ISSUE TITLE
add tags for each version

### ISSUE THREAD

**Issue by maruilian11** [trinary/d3-transform#17]
would you please consider adding tags for each version so that we can add your lib on https://cdnjs.com/ with **git auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5836

**Comment by trinary** [comment]
Just added a tag for the current release. Does this get you what's needed for auto-update?

**Comment by maruilian11** [comment]
yes! if all version tags has been added, this issue could be close. thank you very much!
