### ISSUE TITLE
MIT license or BSD?

### ISSUE THREAD

**Issue by maruilian11** [trinary/d3-transform#18]
hi, recently we want to add your lib on https://cdnjs.com.
i saw bsd license in package.json but MIT in readme.md, I want to confirm this with you.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/5836

**Comment by trinary** [comment]
Just updated package.json to agree with readme/license.txt. Thanks for pointing this out!

**Comment by maruilian11** [comment]
thank you!
